default: help
.PHONY: default


help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make install'
	@echo
	@echo '	$$ make uninstall'
	@echo
	@echo '	$$ make clean'
	@echo
.PHONY: help




install:
	@./install.sh
.PHONY: install


uninstall:
	@./uninstall.sh
.PHONY: uninstall


clean:
	./clean.sh
.PHONY: clean
