
default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make win'
	@echo
.PHONY: help




reset:
	@./reset.sh
.PHONY: reset


win:
	@./win.sh
.PHONY: win


alt:
	@./alt.sh
.PHONY: alt
